server: "hub.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "build": "browserstack-build-1"
  "name": "BStack local test"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "browserstack.local": true
